-- Expand the curated activity library from 28 to 200.
--
-- These are the "you can do this anywhere" ideas: the pool the app draws from
-- when there is no location fix, when the weather pushes you indoors, or when
-- Overpass has nothing to offer. At 28 entries a 30-minute solo session saw the
-- same handful of suggestions within minutes; 200 gives every combination of
-- time, group size and weather something to work with.
--
-- Balanced at 25 per category. Every row carries both languages, because the
-- app has no fallback: a missing title_en renders as an empty card.
--
-- Re-runnable: rows are matched on title_nl, so applying this twice is a no-op.

insert into public.mmd_activities
  (category_id, title_nl, title_en, description_nl, description_en, emoji, min_duration, indoor, tags)
select
  v.category_id, v.title_nl, v.title_en, v.description_nl, v.description_en,
  v.emoji, v.min_duration, v.indoor, v.tags
from (values
  -- ==== Eten & Drinken ====================================================
  ('food', 'Ontbijt uitgebreid buiten de deur', 'Have a long breakfast out', 'Neem de tijd, bestel te veel', 'Take your time, order too much', '🥐', 60, true, array['treat','morning']),
  ('food', 'Bestel het gerecht dat je niet kunt uitspreken', 'Order the dish you cannot pronounce', 'Wijs aan en laat je verrassen', 'Point at it and be surprised', '🍜', 60, true, array['solo','date']),
  ('food', 'Doe een bakkerijronde', 'Do a bakery crawl', 'Drie bakkers, drie keer hetzelfde broodje', 'Three bakeries, the same roll three times', '🥖', 45, false, array['walk','cheap']),
  ('food', 'Proef drie soorten kaas', 'Taste three kinds of cheese', 'Vraag de kaasboer om zijn favoriet', 'Ask the cheesemonger for their favourite', '🧀', 30, true, array['cheap','quick']),
  ('food', 'Zoek de beste friet van de stad', 'Find the best chips in town', 'Vergelijk er minstens twee', 'Compare at least two', '🍟', 45, false, array['cheap','group']),
  ('food', 'Eet aan de bar van een eetcafé', 'Eat at the bar of a pub', 'Alleen eten is geen straf', 'Eating alone is no punishment', '🍺', 60, true, array['solo','evening']),
  ('food', 'Kook met alleen wat er al in huis is', 'Cook with only what is already home', 'Geen boodschappen, wel een maaltijd', 'No shopping, still a meal', '🥘', 60, true, array['home','free']),
  ('food', 'Ga high tea drinken', 'Go for high tea', 'Kleine hapjes, lange middag', 'Small bites, long afternoon', '🫖', 90, true, array['date','treat']),
  ('food', 'Probeer een keuken die je nooit at', 'Try a cuisine you have never had', 'Zoek een land op de kaart en eet het', 'Pick a country off the map and eat it', '🍛', 90, true, array['group','date']),
  ('food', 'Haal ontbijt en eet het in het park', 'Get breakfast and eat it in the park', 'Buiten smaakt alles beter', 'Everything tastes better outside', '🥯', 45, false, array['sunny','cheap']),
  ('food', 'Doe een ijssalon-test', 'Run an ice cream taste test', 'Twee zaken, dezelfde smaak, één winnaar', 'Two shops, one flavour, one winner', '🍦', 30, false, array['quick','group']),
  ('food', 'Bak brood van begin tot eind', 'Bake bread from scratch', 'Kneden, wachten, ruiken', 'Knead, wait, smell', '🍞', 180, true, array['home','rainy']),
  ('food', 'Zoek een ouderwetse snackbar op', 'Track down an old-school snack bar', 'Bestel wat er op het bord staat', 'Order whatever is on the board', '🌭', 30, true, array['cheap','quick']),
  ('food', 'Drink koffie zonder je telefoon', 'Have coffee without your phone', 'Kijk gewoon een half uur naar buiten', 'Just watch the street for half an hour', '☕', 30, true, array['solo','calm']),
  ('food', 'Maak een picknickmand voor iemand anders', 'Pack a picnic basket for someone else', 'Zij hoeven niets te weten', 'They do not need to know a thing', '🧺', 60, true, array['date','home']),
  ('food', 'Ga naar een foodhal', 'Visit a food hall', 'Eén tafel, drie keukens', 'One table, three kitchens', '🍱', 75, true, array['group','rainy']),
  ('food', 'Bestel wat de kok aanraadt', 'Order whatever the chef recommends', 'Geen menukaart, gewoon vragen', 'No menu, just ask', '👨‍🍳', 90, true, array['date','treat']),
  ('food', 'Proef een lokaal bier of een lokale wijn', 'Taste a local beer or wine', 'Vraag waar het vandaan komt', 'Ask where it comes from', '🍷', 60, true, array['evening','solo']),
  ('food', 'Maak verse pasta met de hand', 'Make pasta by hand', 'Meel over de hele keuken, het hoort erbij', 'Flour everywhere is part of it', '🍝', 90, true, array['home','group']),
  ('food', 'Zoek een plek die maar één gerecht serveert', 'Find a place that serves one dish', 'Als ze er maar één maken, is het goed', 'If they only make one, it is good', '🍲', 60, true, array['solo','cheap']),
  ('food', 'Eet ontbijt als avondeten', 'Eat breakfast for dinner', 'Niemand die het merkt', 'Nobody will notice', '🍳', 45, true, array['home','free']),

  -- ==== Cultuur ============================================================
  ('culture', 'Bezoek een kleine galerie', 'Visit a small gallery', 'Vaak gratis, altijd stil', 'Usually free, always quiet', '🖼️', 45, true, array['free','quiet']),
  ('culture', 'Ga naar een poëzieavond', 'Go to a poetry night', 'Luisteren is genoeg', 'Listening is enough', '📜', 90, true, array['evening','quiet']),
  ('culture', 'Bekijk een documentaire in een filmhuis', 'See a documentary at an arthouse', 'Kies op de titel alleen', 'Choose on the title alone', '🎞️', 120, true, array['solo','evening']),
  ('culture', 'Bezoek een open atelier', 'Visit an open studio', 'Vraag de maker waar het over gaat', 'Ask the maker what it is about', '🎨', 60, true, array['weekend','learn']),
  ('culture', 'Loop een gratis stadswandeling met gids', 'Join a free guided city walk', 'Je eigen stad, maar dan uitgelegd', 'Your own city, explained', '🚶', 90, false, array['walk','learn']),
  ('culture', 'Luister naar een klassiek concert', 'Hear a classical concert', 'Ook zonder verstand van muziek', 'You do not need to know music', '🎻', 120, true, array['evening','date']),
  ('culture', 'Bezoek het stadsarchief', 'Visit the city archive', 'Zoek je eigen straat op in 1920', 'Look up your own street in 1920', '🗃️', 90, true, array['quiet','learn']),
  ('culture', 'Kijk naar een repetitie of open podium', 'Watch a rehearsal or open mic', 'Ruw en daarom goed', 'Rough, and better for it', '🎤', 90, true, array['evening','free']),
  ('culture', 'Zoek het oudste gebouw van je buurt', 'Find the oldest building in your area', 'De gevel verklapt het jaartal', 'The facade gives away the year', '🏚️', 60, false, array['walk','free']),
  ('culture', 'Ga naar een boekpresentatie', 'Attend a book launch', 'Gratis wijn, gratis verhaal', 'Free wine, free story', '📕', 90, true, array['evening','quiet']),
  ('culture', 'Bekijk een fototentoonstelling', 'See a photography show', 'Blijf bij één foto twee minuten staan', 'Stand at one photo for two minutes', '📷', 60, true, array['solo','photo']),
  ('culture', 'Ga naar het theater zonder de samenvatting te lezen', 'Go to the theatre without reading the synopsis', 'Laat het stuk zichzelf uitleggen', 'Let the play explain itself', '🎭', 150, true, array['evening','date']),
  ('culture', 'Zoek een beeld in de openbare ruimte', 'Find a public sculpture', 'Loop er een keer helemaal omheen', 'Walk all the way around it once', '🗿', 45, false, array['walk','free']),
  ('culture', 'Bezoek een kerk of moskee op een open dag', 'Visit a place of worship on an open day', 'Kijk omhoog, daar zit het werk', 'Look up, that is where the work is', '⛪', 60, true, array['quiet','learn']),
  ('culture', 'Volg een korte workshop', 'Take a short workshop', 'Twee uur lang ergens slecht in zijn', 'Two hours of being bad at something', '🛠️', 120, true, array['learn','group']),
  ('culture', 'Leen een plaat of dvd in de bibliotheek', 'Borrow a record or DVD at the library', 'Analoog uitzoeken duurt langer en dat is prima', 'Browsing analogue takes longer, which is fine', '💿', 45, true, array['free','solo']),
  ('culture', 'Bekijk de stad vanuit een oude toren', 'See the city from an old tower', 'De trap hoort bij de ervaring', 'The stairs are part of it', '🔔', 60, false, array['photo','learn']),
  ('culture', 'Zoek een muurgedicht op', 'Track down a wall poem', 'Lees het hardop, één keer', 'Read it out loud, once', '✒️', 45, false, array['walk','free']),
  ('culture', 'Bezoek een ambachtelijke werkplaats', 'Visit a craft workshop', 'Kijk hoe iemand iets met de hand maakt', 'Watch someone make something by hand', '⚒️', 60, true, array['learn','solo']),
  ('culture', 'Ga naar een museum in het laatste uur', 'Visit a museum in its final hour', 'Rustiger, goedkoper, en je moet kiezen', 'Quieter, cheaper, and you have to choose', '🏛️', 60, true, array['cheap','quiet']),
  ('culture', 'Luister een lezing over iets vreemds', 'Attend a talk on something odd', 'Hoe onbekender het onderwerp, hoe beter', 'The stranger the subject, the better', '🎙️', 90, true, array['learn','evening']),

  -- ==== Natuur =============================================================
  ('nature', 'Zoek water en volg de oever', 'Find water and follow the bank', 'Sloot, gracht of rivier, alles telt', 'Ditch, canal or river, all count', '🏞️', 60, false, array['walk','calm']),
  ('nature', 'Ga vogels spotten', 'Go birdwatching', 'Stilstaan werkt beter dan zoeken', 'Standing still beats searching', '🦆', 60, false, array['calm','solo']),
  ('nature', 'Loop een bosroute', 'Walk a forest trail', 'Volg de paaltjes en denk nergens aan', 'Follow the markers and think about nothing', '🌲', 90, false, array['walk','active']),
  ('nature', 'Kijk de zon opkomen', 'Watch the sunrise', 'Eén keer per jaar is genoeg om het te onthouden', 'Once a year is enough to remember it', '🌄', 60, false, array['calm','date']),
  ('nature', 'Zoek de grootste boom in de buurt', 'Find the biggest tree nearby', 'Meet hem met je armen', 'Measure it with your arms', '🌳', 45, false, array['free','walk']),
  ('nature', 'Ga wildplukken met een gids of app', 'Go foraging with a guide or app', 'Alleen plukken wat je zeker weet', 'Only pick what you are sure of', '🍄', 90, false, array['learn','free']),
  ('nature', 'Zwem buiten', 'Swim outdoors', 'Koud water, korte duik, lang effect', 'Cold water, short dip, long effect', '🏖️', 60, false, array['sunny','active']),
  ('nature', 'Kijk naar de sterren', 'Look at the stars', 'Zoek het donkerste plekje dat je kunt bereiken', 'Find the darkest spot you can reach', '✨', 60, false, array['evening','date']),
  ('nature', 'Loop op blote voeten door het gras', 'Walk barefoot through the grass', 'Belachelijk simpel, verrassend goed', 'Ridiculously simple, surprisingly good', '🦶', 30, false, array['free','calm']),
  ('nature', 'Bezoek een botanische tuin', 'Visit a botanical garden', 'Ook in de winter, juist in de winter', 'In winter too, especially in winter', '🌷', 75, false, array['calm','date']),
  ('nature', 'Volg een beek stroomopwaarts', 'Follow a stream upstream', 'Kijken hoe ver je komt', 'See how far you get', '💧', 90, false, array['walk','active']),
  ('nature', 'Zoek een plek zonder verkeersgeluid', 'Find a spot with no traffic noise', 'Ze bestaan, ook in de stad', 'They exist, even in the city', '🤫', 45, false, array['calm','solo']),
  ('nature', 'Maak een boswandeling in de regen', 'Take a forest walk in the rain', 'Goede jas, geen excuses', 'Good coat, no excuses', '🌧️', 60, false, array['active','free']),
  ('nature', 'Ga schelpen of stenen zoeken', 'Go looking for shells or stones', 'Neem er precies één mee naar huis', 'Take exactly one home', '🐚', 60, false, array['calm','group']),
  ('nature', 'Tuinier een uur', 'Garden for an hour', 'Balkon telt ook', 'A balcony counts', '🪴', 60, false, array['home','calm']),
  ('nature', 'Zoek de hoogste plek in de omgeving', 'Find the highest point nearby', 'Duin, dijk of parkeerdak', 'Dune, dyke or car park roof', '⛰️', 90, false, array['active','photo']),
  ('nature', 'Wacht tot het donker wordt en kijk toe', 'Wait for dusk and watch it fall', 'Het duurt langer dan je denkt', 'It takes longer than you think', '🌆', 45, false, array['calm','date']),
  ('nature', 'Maak een wandeling over een dijk', 'Walk along a dyke', 'Wind mee heen, wind tegen terug', 'Wind behind you there, against you back', '🌾', 90, false, array['walk','active']),
  ('nature', 'Ga kanoën of suppen', 'Go canoeing or paddleboarding', 'De stad ziet er anders uit vanaf het water', 'The city looks different from the water', '🛶', 120, false, array['active','group']),
  ('nature', 'Zoek een stadspark dat je nog nooit zag', 'Find a city park you have never seen', 'Er is er altijd nog één', 'There is always one more', '🌿', 60, false, array['walk','free']),
  ('nature', 'Tel hoeveel soorten vogels je hoort', 'Count how many bird species you hear', 'Ogen dicht, tien minuten', 'Eyes closed, ten minutes', '🐦', 30, false, array['calm','free']),

  -- ==== Actief =============================================================
  ('active', 'Doe een trappenchallenge', 'Do a stairs challenge', 'Eén trap, vijf keer omhoog', 'One staircase, five times up', '🪜', 30, false, array['active','quick']),
  ('active', 'Ga schaatsen of rolschaatsen', 'Go skating', 'Vallen hoort erbij', 'Falling is part of it', '⛸️', 90, true, array['active','group']),
  ('active', 'Speel een potje straatbasketbal', 'Play some street basketball', 'Er is altijd wel iemand die meedoet', 'Someone always joins in', '🏀', 60, false, array['active','group']),
  ('active', 'Doe een yogales', 'Take a yoga class', 'Achterin staan mag', 'Standing at the back is allowed', '🧘', 75, true, array['calm','active']),
  ('active', 'Ga boulderen', 'Go bouldering', 'Geen touw, wel matten', 'No rope, plenty of mats', '🪨', 90, true, array['active','rainy']),
  ('active', 'Fiets een rondje van 20 kilometer', 'Ride a 20 kilometre loop', 'Kies de route op goed geluk', 'Pick the route at random', '🚴', 90, false, array['active','solo']),
  ('active', 'Doe een buitenworkout in het park', 'Do an outdoor workout in the park', 'Een bankje is een heel sportschool', 'A bench is an entire gym', '💪', 45, false, array['free','active']),
  ('active', 'Speel padel of tennis', 'Play padel or tennis', 'Baan huren kan vaak op het laatste moment', 'Courts are often free last minute', '🎾', 90, false, array['group','active']),
  ('active', 'Ga bowlen', 'Go bowling', 'Slechte schoenen, goede avond', 'Bad shoes, good evening', '🎳', 90, true, array['group','evening']),
  ('active', 'Doe een dansles', 'Take a dance class', 'Beginnerslessen zijn er elke week', 'Beginner classes run every week', '💃', 75, true, array['group','learn']),
  ('active', 'Zwem baantjes tot je niet meer kunt', 'Swim laps until you are done', 'Tel niet mee, zwem gewoon', 'Do not count, just swim', '🏊', 60, true, array['active','solo']),
  ('active', 'Ga midgetgolven', 'Play mini golf', 'Serieus spelen maakt het leuker', 'Taking it seriously makes it better', '⛳', 60, false, array['group','date']),
  ('active', 'Probeer een boksles', 'Try a boxing class', 'Handschoenen kun je lenen', 'You can borrow the gloves', '🥊', 75, true, array['active','learn']),
  ('active', 'Speel tafeltennis', 'Play table tennis', 'In het park staat vaak een betonnen tafel', 'Parks often have a concrete table', '🏓', 45, true, array['group','quick']),
  ('active', 'Loop een parcours van bankje naar bankje', 'Run a bench-to-bench circuit', 'Rennen, oefening, doorlopen', 'Run, exercise, move on', '🏃', 45, false, array['free','active']),
  ('active', 'Probeer schermen of boogschieten', 'Try fencing or archery', 'Proeflessen zijn goedkoper dan je denkt', 'Taster sessions are cheaper than you think', '🏹', 90, true, array['learn','group']),
  ('active', 'Huur een tandem', 'Rent a tandem', 'Afspreken wie stuurt is het halve werk', 'Agreeing who steers is half the job', '🚲', 90, false, array['date','active']),
  ('active', 'Doe een sportles die je nooit zou kiezen', 'Take a class you would never choose', 'Juist die', 'Precisely that one', '🤸', 75, true, array['learn','active']),
  ('active', 'Skate of step een rondje', 'Skate or scoot a lap', 'Het asfalt bepaalt de route', 'The tarmac decides the route', '🛹', 45, false, array['active','quick']),
  ('active', 'Beklim de hoogste trap van de stad', 'Climb the tallest staircase in town', 'Bovenaan is er altijd uitzicht', 'There is always a view at the top', '🧗', 45, false, array['active','photo']),
  ('active', 'Doe een estafette met vrienden', 'Run a relay with friends', 'Verzin de regels onderweg', 'Make up the rules as you go', '🥇', 60, false, array['group','active']),

  -- ==== Shoppen ============================================================
  ('shopping', 'Zoek een platenzaak', 'Find a record shop', 'Koop op de hoes, niet op de naam', 'Buy on the sleeve, not the name', '🎵', 45, true, array['solo','thrift']),
  ('shopping', 'Bezoek een kringloopwinkel', 'Visit a charity shop', 'Begin achterin, daar staat het goede spul', 'Start at the back, that is where the good stuff is', '♻️', 60, true, array['thrift','cheap']),
  ('shopping', 'Koop iets van maximaal vijf euro', 'Buy something for five euros max', 'Het budget maakt de keuze leuker', 'The budget makes it more fun', '🪙', 30, true, array['cheap','quick']),
  ('shopping', 'Zoek een winkel die maar één ding verkoopt', 'Find a shop that sells one thing', 'Knopen, kwasten, kurken, wat dan ook', 'Buttons, brushes, corks, whatever', '🔑', 45, true, array['solo','quiet']),
  ('shopping', 'Ga naar een rommelmarkt', 'Go to a flea market', 'Vroeg komen of laat afdingen', 'Come early or haggle late', '🪑', 90, false, array['weekend','thrift']),
  ('shopping', 'Lees één hoofdstuk in een boekwinkel', 'Read one chapter in a bookshop', 'Kopen mag, hoeft niet', 'Buying is allowed, not required', '📗', 45, true, array['quiet','solo']),
  ('shopping', 'Koop een cadeau voor iemand zonder reden', 'Buy a present for no reason', 'Geen verjaardag nodig', 'No birthday needed', '🎁', 45, true, array['treat','date']),
  ('shopping', 'Zoek een kaaswinkel of delicatessenzaak', 'Find a cheese shop or deli', 'Vraag om een stukje om te proeven', 'Ask for a taster', '🧀', 30, true, array['cheap','quick']),
  ('shopping', 'Bezoek een plantenwinkel', 'Visit a plant shop', 'Neem er eentje mee die weinig licht nodig heeft', 'Take home one that needs little light', '🪴', 45, true, array['calm','home']),
  ('shopping', 'Dwaal door een bouwmarkt en bedenk een project', 'Wander a hardware shop and plan a project', 'Kopen mag later', 'You can buy later', '🔧', 60, true, array['home','learn']),
  ('shopping', 'Koop bloemen voor je eigen keukentafel', 'Buy flowers for your own kitchen table', 'Niemand anders gaat het doen', 'Nobody else is going to', '💐', 30, true, array['treat','quick']),
  ('shopping', 'Ga naar een boerenmarkt', 'Go to a farmers market', 'Vraag wat er nu in het seizoen zit', 'Ask what is in season right now', '🥕', 60, false, array['weekend','free']),
  ('shopping', 'Zoek een winkel in een taal die je niet spreekt', 'Find a shop in a language you do not speak', 'Wijzen werkt overal', 'Pointing works everywhere', '🏪', 45, true, array['learn','solo']),
  ('shopping', 'Bezoek een muziekinstrumentenwinkel', 'Visit an instrument shop', 'Vraag of je iets mag proberen', 'Ask if you can try something', '🎸', 45, true, array['learn','solo']),
  ('shopping', 'Koop tweedehands wat je nieuw wilde', 'Buy second-hand what you wanted new', 'Half zo duur, twee keer zo leuk', 'Half the price, twice the fun', '👕', 60, true, array['thrift','cheap']),
  ('shopping', 'Zoek een papierwinkel of kantoorboekhandel', 'Find a stationery shop', 'Eén goed schrift verandert je week', 'One good notebook changes your week', '📎', 45, true, array['calm','solo']),
  ('shopping', 'Ruil kleren met een vriend', 'Swap clothes with a friend', 'Gratis, en je kast wordt leger', 'Free, and your wardrobe gets lighter', '🔁', 60, true, array['group','free']),
  ('shopping', 'Bezoek een winkel die er al vijftig jaar zit', 'Visit a shop that has been there fifty years', 'Vraag naar het begin', 'Ask about the early days', '🕰️', 45, true, array['learn','solo']),
  ('shopping', 'Koop ingrediënten voor een gerecht dat je niet kent', 'Buy ingredients for a dish you do not know', 'Recept zoek je thuis wel', 'Find the recipe once you are home', '🛒', 45, true, array['home','learn']),
  ('shopping', 'Kijk rond in een dierenwinkel', 'Browse a pet shop', 'De aquaria zijn gratis rust', 'The aquariums are free calm', '🐠', 30, true, array['quick','calm']),
  ('shopping', 'Bekijk een designwinkel zonder iets te kopen', 'Browse a design shop and buy nothing', 'Kijken is ook een activiteit', 'Looking is an activity too', '🪞', 45, true, array['free','solo']),
  ('shopping', 'Koop een spel en speel het meteen', 'Buy a game and play it right away', 'Doos open op het terras', 'Open the box on the terrace', '🎲', 90, true, array['group','home']),

  -- ==== Uitgaan ============================================================
  ('nightlife', 'Dans tot het licht wordt', 'Dance until it gets light', 'Eén keer per jaar mag', 'Once a year is allowed', '🕺', 180, true, array['group','evening']),
  ('nightlife', 'Zoek een bar met live jazz', 'Find a bar with live jazz', 'Meestal geen entree', 'Usually no cover charge', '🎷', 120, true, array['date','evening']),
  ('nightlife', 'Doe karaoke', 'Do karaoke', 'Kies een nummer dat je niet kunt zingen', 'Pick a song you cannot sing', '🎤', 120, true, array['group','evening']),
  ('nightlife', 'Ga naar een filmavond in een café', 'Catch a film night in a café', 'Vaak gratis, altijd gezellig', 'Often free, always warm', '🎬', 120, true, array['evening','cheap']),
  ('nightlife', 'Speel een bordspel in de kroeg', 'Play a board game at the pub', 'De meeste cafés hebben een kast', 'Most pubs have a cupboard', '🎲', 90, true, array['group','evening']),
  ('nightlife', 'Zoek het beste dakterras', 'Find the best rooftop terrace', 'Hoger is bijna altijd beter', 'Higher is nearly always better', '🌃', 90, false, array['date','photo']),
  ('nightlife', 'Ga naar een open mic', 'Go to an open mic', 'Kijken telt ook als meedoen', 'Watching counts as taking part', '🎙️', 120, true, array['evening','free']),
  ('nightlife', 'Drink één cocktail die je niet kent', 'Have one cocktail you have never heard of', 'Laat de barman kiezen', 'Let the bartender choose', '🍸', 60, true, array['date','treat']),
  ('nightlife', 'Bezoek een studentencafé', 'Visit a student bar', 'Goedkoop en luid', 'Cheap and loud', '🍻', 90, true, array['group','cheap']),
  ('nightlife', 'Maak een avondwandeling door de verlichte stad', 'Walk the lit-up city at night', 'Dezelfde straten, ander gevoel', 'Same streets, different feeling', '🌙', 60, false, array['free','calm']),
  ('nightlife', 'Ga naar een clubavond van een onbekend genre', 'Go to a club night in an unknown genre', 'Blijf minstens een uur', 'Stay at least an hour', '🔊', 180, true, array['group','evening']),
  ('nightlife', 'Speel poolbiljart', 'Play a game of pool', 'Best of three', 'Best of three', '🎱', 90, true, array['group','evening']),
  ('nightlife', 'Zoek een bar met alleen kaarslicht', 'Find a candlelit bar', 'Praten gaat er vanzelf beter', 'Talking comes easier there', '🕯️', 90, true, array['date','calm']),
  ('nightlife', 'Ga naar een late voorstelling', 'Catch a late show', 'Na elven is het publiek anders', 'After eleven the crowd is different', '🎪', 120, true, array['evening','date']),
  ('nightlife', 'Ga naar een silent disco', 'Go to a silent disco', 'Koptelefoon af en luisteren naar de stilte', 'Take the headphones off and hear the silence', '🎧', 150, true, array['group','evening']),
  ('nightlife', 'Drink alcoholvrij en blijf net zo lang', 'Go alcohol-free and stay just as long', 'Werkt beter dan je denkt', 'Works better than you would think', '🥤', 120, true, array['group','evening']),
  ('nightlife', 'Zoek een kroeg waar niemand op zijn telefoon kijkt', 'Find a pub where nobody is on their phone', 'Ze bestaan nog', 'They still exist', '📵', 90, true, array['group','calm']),
  ('nightlife', 'Ga naar een comedy-avond', 'Catch a comedy night', 'Ga niet vooraan zitten', 'Do not sit at the front', '😂', 120, true, array['group','evening']),
  ('nightlife', 'Bekijk een lokale band', 'See a local band', 'Koop hun plaat bij de deur', 'Buy their record at the door', '🎼', 120, true, array['evening','cheap']),
  ('nightlife', 'Zoek de laatste bar die nog open is', 'Find the last bar still open', 'Er is er altijd één', 'There is always one', '🌜', 90, true, array['evening','group']),
  ('nightlife', 'Doe een pubquiz in je eentje', 'Do a pub quiz on your own', 'Je verliest, maar je praat met iedereen', 'You lose, but you talk to everyone', '🧩', 120, true, array['solo','evening']),
  ('nightlife', 'Ga naar een dansavond voor beginners', 'Go to a beginners dance night', 'Iedereen daar kan het ook niet', 'Nobody there can do it either', '🪩', 120, true, array['learn','group']),

  -- ==== Bezienswaardig =====================================================
  ('landmark', 'Zoek het geografische middelpunt van je stad', 'Find your city geographic centre', 'Er staat zelden iets bijzonders', 'There is rarely anything special there', '📍', 60, false, array['walk','learn']),
  ('landmark', 'Bekijk een brug van onderaf', 'Look at a bridge from below', 'Het mooiste zit aan de onderkant', 'The best part is underneath', '🌉', 45, false, array['photo','walk']),
  ('landmark', 'Lees de vertrekborden op het station', 'Read the departure boards at the station', 'Bedenk waar je heen zou gaan', 'Decide where you would go', '🚉', 30, true, array['solo','quick']),
  ('landmark', 'Zoek een standbeeld en lees wie het was', 'Find a statue and learn who it was', 'Meestal iemand die je niet kent', 'Usually someone you have never heard of', '🗿', 45, false, array['learn','free']),
  ('landmark', 'Loop de hele hoofdstraat uit', 'Walk the entire main street', 'Van begin tot einde, zonder afslag', 'Beginning to end, no turning off', '🛣️', 75, false, array['walk','free']),
  ('landmark', 'Bezoek een begraafplaats met verhalen', 'Visit a cemetery with stories', 'Lees de oudste steen die je vindt', 'Read the oldest stone you find', '🪦', 60, false, array['quiet','learn']),
  ('landmark', 'Zoek de smalste steeg', 'Find the narrowest alley', 'Schouders passen net', 'Your shoulders will just fit', '🧱', 45, false, array['walk','photo']),
  ('landmark', 'Ga naar een haven of kade', 'Go to a harbour or quay', 'Kijken naar boten telt als rust', 'Watching boats counts as rest', '⚓', 60, false, array['calm','photo']),
  ('landmark', 'Zoek een gebouw uit je geboortejaar', 'Find a building from the year you were born', 'De gevel verklapt het meestal', 'The facade usually gives it away', '🏢', 60, false, array['learn','solo']),
  ('landmark', 'Bekijk de stad vanaf het water', 'See the city from the water', 'Rondvaart of pontje, allebei goed', 'Boat tour or ferry, both work', '🚤', 90, false, array['date','photo']),
  ('landmark', 'Zoek een gedenkteken en sta er even stil', 'Find a memorial and pause there', 'Twee minuten is genoeg', 'Two minutes is enough', '🕊️', 30, false, array['quiet','free']),
  ('landmark', 'Loop een rondje om het oudste plein', 'Circle the oldest square', 'Alle vier de zijden', 'All four sides', '🏟️', 45, false, array['walk','free']),
  ('landmark', 'Zoek een watertoren', 'Find a water tower', 'Ze staan er nog bijna overal', 'They are still standing nearly everywhere', '🗼', 60, false, array['walk','photo']),
  ('landmark', 'Bezoek een sluis of gemaal', 'Visit a lock or pumping station', 'Wacht tot er een boot doorgaat', 'Wait for a boat to pass through', '🌊', 60, false, array['learn','walk']),
  ('landmark', 'Zoek de mooiste voordeur van de buurt', 'Find the finest front door in the area', 'Je gaat er anders van lopen kijken', 'It changes how you look around', '🚪', 45, false, array['photo','walk']),
  ('landmark', 'Ga naar het uiterste noorden van je stad', 'Go to the far north of your city', 'Daar houdt het gewoon op', 'That is simply where it stops', '🧭', 90, false, array['walk','active']),
  ('landmark', 'Bezoek een molen', 'Visit a windmill', 'Vaak mag je naar binnen', 'You can often go inside', '🌬️', 60, false, array['learn','photo']),
  ('landmark', 'Zoek een gevelsteen en ontcijfer hem', 'Find a wall stone and decipher it', 'Meestal een beroep of een jaartal', 'Usually a trade or a year', '🪧', 45, false, array['learn','walk']),
  ('landmark', 'Loop naar je eerste adres in deze stad', 'Walk to your first address in this town', 'Kijk hoe het veranderd is', 'See how it has changed', '🏠', 75, false, array['solo','walk']),
  ('landmark', 'Zoek de beste plek voor zonsondergang', 'Find the best spot for sunset', 'Kom een half uur te vroeg', 'Arrive half an hour early', '🌇', 60, false, array['date','photo']),
  ('landmark', 'Loop door een tunnel of onderdoorgang', 'Walk through a tunnel or underpass', 'Roep één keer, om de echo', 'Shout once, for the echo', '🚇', 30, false, array['quick','walk']),
  ('landmark', 'Zoek een gebouw dat iedereen lelijk vindt', 'Find a building everyone calls ugly', 'Kijk of je het ermee eens bent', 'See if you agree', '🏗️', 45, false, array['walk','free']),

  -- ==== Ontspannen =========================================================
  ('relax', 'Lees een uur in het park', 'Read for an hour in the park', 'Eén hoofdstuk verder dan je van plan was', 'One chapter further than planned', '📖', 60, false, array['calm','solo']),
  ('relax', 'Doe een dutje zonder wekker', 'Nap without an alarm', 'Wakker worden wanneer het klaar is', 'Wake up when it is done', '😴', 60, true, array['home','calm']),
  ('relax', 'Ga naar een badhuis of hammam', 'Visit a bathhouse or hammam', 'Warm, stil, geen telefoon', 'Warm, quiet, no phone', '🛁', 120, true, array['treat','calm']),
  ('relax', 'Zit een half uur op één bankje', 'Sit on one bench for half an hour', 'Niet opstaan, gewoon kijken', 'Do not get up, just watch', '🪑', 30, false, array['free','calm']),
  ('relax', 'Luister een album van begin tot eind', 'Listen to an album start to finish', 'Zonder overslaan', 'No skipping', '🎧', 45, true, array['home','calm']),
  ('relax', 'Doe niets, letterlijk', 'Do nothing, literally', 'Een half uur, geen scherm', 'Half an hour, no screen', '🫧', 30, true, array['free','calm']),
  ('relax', 'Neem een lang bad met muziek', 'Take a long bath with music', 'Bijvullen tot het te warm is', 'Top it up until it is too hot', '🛀', 60, true, array['home','treat']),
  ('relax', 'Schrijf een brief op papier', 'Write a letter on paper', 'Versturen mag, hoeft niet', 'Sending it is optional', '✉️', 45, true, array['calm','solo']),
  ('relax', 'Zet je telefoon drie uur uit', 'Turn your phone off for three hours', 'Echt uit, niet op stil', 'Actually off, not silent', '📴', 180, true, array['free','calm']),
  ('relax', 'Doe een ademhalingsoefening buiten', 'Do a breathing exercise outdoors', 'Vier tellen in, zes tellen uit', 'Four counts in, six counts out', '🌬️', 30, false, array['free','calm']),
  ('relax', 'Ga naar een sauna', 'Go to a sauna', 'Koud afspoelen hoort erbij', 'The cold rinse is part of it', '🧖', 120, true, array['treat','relax']),
  ('relax', 'Teken wat je voor je ziet', 'Draw what is in front of you', 'Lelijk mag, het gaat om het kijken', 'Ugly is fine, it is about looking', '✏️', 45, false, array['calm','solo']),
  ('relax', 'Kijk een film die je al kent', 'Watch a film you already know', 'Geen verrassingen, precies de bedoeling', 'No surprises, exactly the point', '🍿', 120, true, array['home','rainy']),
  ('relax', 'Maak een playlist voor je week', 'Make a playlist for your week', 'Eén nummer per dag', 'One track per day', '🎶', 45, true, array['home','calm']),
  ('relax', 'Boek een massage', 'Book a massage', 'Een uur waarin je niets hoeft', 'An hour where nothing is required of you', '💆', 60, true, array['treat','relax']),
  ('relax', 'Ruim precies één la op', 'Clear out exactly one drawer', 'Meer niet, dat is de regel', 'No more, that is the rule', '🗄️', 45, true, array['home','calm']),
  ('relax', 'Drink thee en kijk uit het raam', 'Drink tea and look out the window', 'Zonder iets anders erbij', 'Nothing else alongside it', '🍵', 30, true, array['home','calm']),
  ('relax', 'Maak een lange wandeling zonder doel', 'Take a long walk with no destination', 'Sla af waar het je uitkomt', 'Turn wherever you feel like', '🚶', 90, false, array['walk','calm']),
  ('relax', 'Slaap uit en ontbijt in bed', 'Sleep in and have breakfast in bed', 'Kruimels horen erbij', 'The crumbs are part of it', '🛏️', 90, true, array['home','treat']),
  ('relax', 'Leg een puzzel', 'Do a jigsaw puzzle', 'Randjes eerst', 'Edges first', '🧩', 90, true, array['home','rainy']),
  ('relax', 'Bel iemand die je te lang niet sprak', 'Call someone you have not spoken to in ages', 'Geen aanleiding nodig', 'No reason needed', '📞', 45, true, array['home','calm']),
  ('relax', 'Zoek de stilste plek in de stad', 'Find the quietest spot in the city', 'Luister eerst, kijk daarna', 'Listen first, look after', '🤫', 60, false, array['calm','solo'])
) as v(category_id, title_nl, title_en, description_nl, description_en, emoji, min_duration, indoor, tags)
where not exists (
  select 1 from public.mmd_activities a where a.title_nl = v.title_nl
);
